/* DECLARE VARIABLE */
DECLARE @COLS AS NVARCHAR(MAX), @QUERY  AS NVARCHAR(MAX)

/* GET ROOM SIZE AND SET AS COLUMN */
SELECT @COLS = STUFF(( SELECT ',' + QUOTENAME(DESCRIPTION) 
					   FROM BED
					   GROUP BY DESCRIPTION, ID_PK
					   ORDER BY ID_PK
					   FOR XML PATH(''), TYPE
					  ).value('.', 'NVARCHAR(MAX)') 
					,1,1,'')

SET @QUERY = N'SELECT ID_PK, DESCRIPTION,' + @COLS + 
			 N'FROM ( SELECT SETTING.ID_PK, SETTING.DESCRIPTION, BED.DESCRIPTION AS BED 
					  FROM BED_SETTING, BED, SETTING
					  WHERE BED_SETTING.BED_FK = BED.ID_PK
					  AND BED_SETTING.SETTING_FK = SETTING.ID_PK 
					 ) AS SOURCE 
			   PIVOT ( COUNT(BED)
					   FOR BED IN (' + @COLS + N')
					 ) AS PIVOTTABLE'

EXEC SP_EXECUTESQL @QUERY;