SELECT ID_PK, DESCRIPTION, [SINGLE], [DOUBLE], [SINGLE]*1+[DOUBLE]*2 AS TOTAL
FROM
( SELECT SETTING.ID_PK, SETTING.DESCRIPTION, BED.DESCRIPTION AS BED 
  FROM BED_SETTING, BED, SETTING
  WHERE BED_SETTING.BED_FK = BED.ID_PK
  AND BED_SETTING.SETTING_FK = SETTING.ID_PK ) AS SOURCE
PIVOT
( COUNT(BED)
  FOR BED IN ([SINGLE],[DOUBLE])) AS PIVOTTABLE