SELECT BED_SETTING.ID_PK, SETTING, BED, ISNULL(NUM,0)
FROM (  SELECT        SETTING.DESCRIPTION AS SETTING, BED.DESCRIPTION AS BED,
					  SETTING.ID_PK AS SETTING_ID, BED.ID_PK AS BED_ID
		FROM            SETTING, BED
		WHERE        (SETTING.DESCRIPTION = 'SETTING 1') ) AS TABLE_1
	 LEFT OUTER JOIN BED_SETTING ON SETTING_ID = SETTING_FK
	                             AND BED_ID = BED_FK